name: torch5
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py37h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1i=h27cfd23_0
  - pip=20.3.3=py37h06a4308_0
  - python=3.7.9=h7579374_0
  - readline=8.0=h7b6447c_0
  - setuptools=51.0.0=py37h06a4308_2
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - cycler==0.10.0
    - datasets==1.1.2
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.3
    - entrypoints==0.3
    - filelock==3.0.12
    - idna==2.10
    - importlib-metadata==3.3.0
    - ipykernel==5.4.2
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.2
    - jedi==0.18.0
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - multiprocess==0.70.11.1
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.6
    - numpy==1.19.4
    - packaging==20.8
    - pandas==1.2.0
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - ptyprocess==0.7.0
    - pyarrow==2.0.0
    - pycparser==2.20
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pyzmq==20.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - regex==2020.11.13
    - requests==2.25.1
    - sacremoses==0.0.43
    - scikit-learn==0.24.0
    - scipy==1.5.4
    - seaborn==0.11.1
    - send2trash==1.5.0
    - sentencepiece==0.1.94
    - six==1.15.0
    - sklearn==0.0
    - terminado==0.9.1
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tokenizers==0.9.4
    - torch==1.7.1
    - torchvision==0.8.2
    - tornado==6.1
    - tqdm==4.49.0
    - traitlets==5.0.5
    - transformers==4.2.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xxhash==2.0.0
    - zipp==3.4.0
prefix: /home/dsi/eladbz/anaconda3/envs/torch5

